# Generated by Django 5.0.6 on 2024-10-01 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0001_initial'),
        ('Ip_Workbench', '0001_initial'),
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Billing_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceType', models.CharField(default='', max_length=30)),
                ('Physician_Type', models.CharField(blank=True, max_length=30, null=True)),
                ('ServiceStatus', models.CharField(default='Completed', max_length=30)),
                ('Units', models.CharField(blank=True, max_length=30, null=True)),
                ('DrugName', models.CharField(blank=True, max_length=30, null=True)),
                ('DrugStatus', models.CharField(default='Pending', max_length=30)),
                ('RadiologyTest', models.CharField(blank=True, max_length=30, null=True)),
                ('RadiologySatus', models.CharField(default='Pending', max_length=30)),
                ('LabTest', models.CharField(blank=True, max_length=30, null=True)),
                ('LabTestStatus', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Created_by', models.CharField(default='', max_length=30)),
                ('BillingDataList_ID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontoffice.ip_billing_queuelist_detials')),
                ('Physician', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.doctor_professform_detials')),
                ('Procedure', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.procedure_master_details')),
                ('Registration_Id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_details_Registration_Id', to='Frontoffice.patient_ip_registration_detials')),
                ('Service', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_details_Service', to='Masters.service_master_details')),
            ],
        ),
    ]
