# Generated by Django 5.0.6 on 2024-10-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ip_Workbench', '0002_ip_billing_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip_preopchecklist_details',
            old_name='PulseRateRemarks',
            new_name='VoidedOrCatheroizedRemarks',
        ),
        migrations.RemoveField(
            model_name='ip_preopchecklist_details',
            name='RespRateRemarks',
        ),
        migrations.RemoveField(
            model_name='ip_preopchecklist_details',
            name='VoidedAmountRemarks',
        ),
        migrations.RemoveField(
            model_name='ip_preopchecklist_details',
            name='VoidedTimeRemarks',
        ),
        migrations.AddField(
            model_name='ip_preopchecklist_details',
            name='VoidedOrCatheroized',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ip_preopchecklist_details',
            name='PulseRate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ip_preopchecklist_details',
            name='RespRate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ip_preopchecklist_details',
            name='VoidedAmount',
            field=models.CharField(max_length=200),
        ),
    ]
