# Generated by Django 5.0.6 on 2024-10-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0001_initial'),
        ('Ip_Workbench', '0003_rename_pulserateremarks_ip_preopchecklist_details_voidedorcatheroizedremarks_and_more'),
        ('Masters', '0002_labtestname_details_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceType', models.CharField(default='Consultation', max_length=30)),
                ('Physician_Type', models.CharField(blank=True, max_length=30, null=True)),
                ('Units', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Created_by', models.CharField(default='', max_length=30)),
                ('Physician', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.doctor_professform_detials')),
                ('Registration_Id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IP_Consultation_details_Registration_Id', to='Frontoffice.patient_ip_registration_detials')),
            ],
        ),
    ]
