# Generated by Django 5.0.6 on 2024-10-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ip_Workbench', '0004_ip_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_consultation',
            name='Status',
            field=models.CharField(default='UnPaid', max_length=30),
        ),
    ]
