# Generated by Django 5.0.6 on 2024-10-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestname_details',
            name='Types',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='labtestname_details',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testlocation', to='Masters.location_detials'),
        ),
        migrations.CreateModel(
            name='External_LabDetails',
            fields=[
                ('External_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('LabName', models.CharField(max_length=50)),
                ('PhoneNo', models.CharField(max_length=30)),
                ('Address', models.TextField()),
                ('Pincode', models.CharField(max_length=30)),
                ('RegisterNo', models.CharField(max_length=40)),
                ('Email', models.CharField(max_length=40)),
                ('Lablocation', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('Status', models.CharField(default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='external_location', to='Masters.location_detials')),
            ],
            options={
                'db_table': 'External_LabDetails',
            },
        ),
        migrations.CreateModel(
            name='External_LabAmount_Details',
            fields=[
                ('OutSource_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('OutSourcePrev_Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('OutSourceLabAmount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_by', models.CharField(max_length=30)),
                ('Status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Test_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outsource', to='Masters.labtestname_details')),
                ('OutSourceLabName', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outsource_location', to='Masters.external_labdetails')),
            ],
            options={
                'db_table': 'External_LabAmount_Details',
            },
        ),
    ]
