# Generated by Django 5.0.6 on 2024-09-30 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN_Entry_Details',
            fields=[
                ('GRN_Number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Supplier_BillNumber', models.IntegerField()),
                ('Supplier_BillDate', models.DateField()),
                ('Supplier_BillDueDate', models.DateField()),
                ('Supplier_BillAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ReceivingPersion', models.CharField(max_length=100)),
                ('GRNFile_Attachment', models.BinaryField(blank=True, default=None, null=True)),
                ('TaxableTotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TaxTotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalDiscountMethod', models.CharField(max_length=20)),
                ('TotalDiscountType', models.CharField(max_length=20)),
                ('TotalDiscountValue', models.IntegerField()),
                ('FinalTaxableTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FinalTaxTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FinalTotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('RountOff', models.DecimalField(decimal_places=2, max_digits=5)),
                ('NetAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BillDiscountMethod', models.CharField(max_length=30)),
                ('GRN_Status', models.CharField(default='Waiting For Approve', max_length=30)),
                ('Create_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('GRNLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRNLocation', to='Masters.location_detials')),
                ('Supplier_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRN_Supplier', to='Masters.supplier_master_details')),
            ],
            options={
                'db_table': 'GRN_Entry_Details',
            },
        ),
        migrations.CreateModel(
            name='CentralStore_Stock_Details',
            fields=[
                ('Stock_Id', models.AutoField(primary_key=True, serialize=False)),
                ('BatchNo', models.CharField(max_length=20)),
                ('Manufacture_Date', models.CharField(max_length=20)),
                ('Expiry_Date', models.CharField(max_length=20)),
                ('ExpiryStatus', models.CharField(default='NotExpired', max_length=20)),
                ('TotalQuantity', models.IntegerField()),
                ('SoldQuantity', models.IntegerField(default=0)),
                ('AvailableQuantity', models.IntegerField()),
                ('MRP_Selling_Price_Taxable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tax_Percentage', models.IntegerField()),
                ('MRP_Selling_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Create_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Stock_Item_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Masters.medical_productmaster_details')),
                ('GRN_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.grn_entry_details')),
            ],
            options={
                'db_table': 'CentralStore_Stock_Details',
            },
        ),
        migrations.CreateModel(
            name='GRN_Items_Entry_Details',
            fields=[
                ('GRN_Item_Number', models.AutoField(primary_key=True, serialize=False)),
                ('Pack_MRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('GRN_Rate_Per_Pack_Taxable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tax_Type', models.CharField(max_length=20)),
                ('Tax_Percentage', models.IntegerField()),
                ('GRN_Rate_Per_Pack', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order_Qty', models.IntegerField()),
                ('Bill_Qty', models.IntegerField()),
                ('Received_Qty', models.IntegerField()),
                ('Pending_Qty', models.IntegerField(default=0)),
                ('Total_Sellable_Qty', models.IntegerField()),
                ('Sellable_Qty_MRP', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pack_Total_Taxable_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Tax_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pack_Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BatchNo', models.CharField(max_length=20)),
                ('Manufacture_Date', models.CharField(max_length=20)),
                ('Expiry_Date', models.CharField(max_length=20)),
                ('Discount_Method', models.CharField(max_length=20)),
                ('Discount_Type', models.CharField(max_length=20)),
                ('Discount_Value', models.IntegerField()),
                ('FinalTotalPackTaxableAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FinalTotalTaxAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FinalTotalPackAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Create_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('GRN_Item_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRN_Item_Detailes', to='Masters.medical_productmaster_details')),
                ('GRN_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grn_Number_ForItems', to='Inventory.grn_entry_details')),
            ],
            options={
                'db_table': 'GRN_Items_Entry_Details',
            },
        ),
        migrations.CreateModel(
            name='Purchase_Order_Details',
            fields=[
                ('PurchaseOrder_Number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Order_Date', models.DateField()),
                ('Delivery_Date', models.DateField()),
                ('Total_Order_Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PO_Status', models.CharField(default='Waiting For Approve', max_length=30)),
                ('Create_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('Billing_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_BillAddress', to='Masters.clinic_detials')),
                ('Billing_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_BillLocation', to='Masters.location_detials')),
                ('Shipping_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_ShippAddress', to='Masters.clinic_detials')),
                ('Shipping_Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_ShippLocation', to='Masters.location_detials')),
                ('Supplier_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_SupplierID', to='Masters.supplier_master_details')),
            ],
            options={
                'db_table': 'Purchase_Order_Details',
            },
        ),
        migrations.AddField(
            model_name='grn_entry_details',
            name='PO_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GRN_PO_Number', to='Inventory.purchase_order_details'),
        ),
        migrations.CreateModel(
            name='Purchase_Order_Item_Details',
            fields=[
                ('PO_Item_Number', models.AutoField(primary_key=True, serialize=False)),
                ('PO_Order_Qty', models.CharField(max_length=20)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Received_Qty', models.IntegerField(default=0)),
                ('Balance_Qty', models.IntegerField(default=0)),
                ('Item_Status', models.CharField(default='Waiting For Approve', max_length=20)),
                ('Reason', models.TextField()),
                ('Create_by', models.CharField(max_length=100)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
                ('Update_at', models.DateTimeField(auto_now=True)),
                ('PO_Item_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PO_Item_ID', to='Masters.supplier_product_details')),
                ('PurchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItemTable_PO_Number', to='Inventory.purchase_order_details')),
            ],
            options={
                'db_table': 'Purchase_Order_Item_Details',
            },
        ),
    ]
