# Generated by Django 5.0.6 on 2024-10-03 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_labtestname_details_types_and_more'),
        ('OutPatient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_request_details',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='lab_request_selected_details',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='lab_request_selected_details',
            name='CategoryType',
        ),
        migrations.RemoveField(
            model_name='lab_request_selected_details',
            name='Code',
        ),
        migrations.RemoveField(
            model_name='lab_request_selected_details',
            name='Location',
        ),
        migrations.AddField(
            model_name='lab_request_details',
            name='FavouriteCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.testname_favourites'),
        ),
        migrations.AddField(
            model_name='lab_request_details',
            name='IndivitualCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.labtestname_details'),
        ),
        migrations.AddField(
            model_name='lab_request_selected_details',
            name='IndivitualCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.labtestname_details'),
        ),
        migrations.AddField(
            model_name='lab_request_selected_details',
            name='OutSource_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Masters.external_labamount_details'),
        ),
    ]
