# Generated by Django 5.0.6 on 2024-10-07 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0001_initial'),
        ('Masters', '0002_labtestname_details_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_Billing_Table_Detials',
            fields=[
                ('Billing_Invoice_No', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Billing_Date', models.DateField()),
                ('Billing_Type', models.CharField(max_length=150)),
                ('Select_Discount', models.CharField(max_length=50)),
                ('Discount_Type', models.CharField(max_length=30)),
                ('Discount_Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Items', models.IntegerField()),
                ('Total_Qty', models.IntegerField()),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_GSTAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Net_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Round_Off', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Paid_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Balance_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Bill_Status', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=100)),
                ('updated_by', models.CharField(default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Doctor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Doctor_Id', to='Masters.doctor_personal_form_detials')),
                ('Patient_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Patient_Id', to='Frontoffice.patient_detials')),
                ('Register_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Patient_Id', to='Frontoffice.patient_appointment_registration_detials')),
                ('Visit_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Visit_Id', to='Frontoffice.patient_visit_detials')),
            ],
        ),
    ]
