# Generated by Django 5.0.6 on 2024-10-07 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0002_ip_billing_table_detials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_billing_table_detials',
            name='Visit_Id',
        ),
        migrations.CreateModel(
            name='IP_Billing_Items_Table_Detials',
            fields=[
                ('Items_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Service_Type', models.CharField(max_length=100)),
                ('Service_Code', models.CharField(max_length=30)),
                ('Service_Name', models.CharField(max_length=350)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.IntegerField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount_Type', models.CharField(max_length=30)),
                ('Discount_Value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Taxable_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Tax_Percentage', models.IntegerField()),
                ('Tax_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Item_Status', models.CharField(max_length=30)),
                ('Billing_Invoice_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items_Table_IP_Billing_Invoice_No', to='Frontoffice.ip_billing_table_detials')),
            ],
            options={
                'db_table': 'IP_Billing_Items_Table_Detials',
            },
        ),
        migrations.CreateModel(
            name='Multiple_Payment_Table_IP_Detials',
            fields=[
                ('S_No', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Type', models.CharField(max_length=70)),
                ('Cart_Type', models.CharField(max_length=30)),
                ('Cheque_No', models.CharField(max_length=20)),
                ('Bank_Name', models.CharField(max_length=50)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Invoice_No', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Multiple_Payment_IP_Billing_Invoice', to='Frontoffice.ip_billing_items_table_detials')),
            ],
            options={
                'db_table': 'Multiple_Payment_Table_IP_Detials',
            },
        ),
    ]
