# Generated by Django 5.0.6 on 2024-10-07 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0003_remove_ip_billing_table_detials_visit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip_billing_table_detials',
            name='Visit_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Visit_Id', to='Frontoffice.patient_visit_detials'),
            preserve_default=False,
        ),
    ]
