# Generated by Django 5.0.6 on 2024-10-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0004_ip_billing_table_detials_visit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_billing_table_detials',
            name='Register_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IP_Billing_Patient_Id', to='Frontoffice.patient_ip_registration_detials'),
        ),
    ]
