# Generated by Django 5.0.6 on 2024-10-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0006_remove_ip_billing_items_table_detials_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_billing_items_table_detials',
            name='Discount_Type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ip_billing_items_table_detials',
            name='Quantity',
            field=models.CharField(default=30, max_length=30),
        ),
    ]
