# Generated by Django 5.0.6 on 2024-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0007_alter_ip_billing_items_table_detials_discount_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip_billing_items_table_detials',
            name='Quantity',
            field=models.CharField(default='', max_length=30),
        ),
    ]
