# Generated by Django 5.0.6 on 2024-10-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontoffice', '0008_alter_ip_billing_items_table_detials_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_payment_table_ip_detials',
            name='Invoice_No',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Multiple_Payment_IP_Billing_Invoice', to='Frontoffice.ip_billing_table_detials'),
        ),
    ]
